// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgvHYt4YGyS--kTlsAv3Ko64WzNwI3oNA',
    appId: '1:1086331368779:android:c66c08991e839e5f07e4ce',
    messagingSenderId: '1086331368779',
    projectId: 'learnfirebase-13aa0',
    storageBucket: 'learnfirebase-13aa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX-xqnLFYE5TSuotLM4xC6ffNueeKjv6k',
    appId: '1:1086331368779:ios:1c11496ef741e07507e4ce',
    messagingSenderId: '1086331368779',
    projectId: 'learnfirebase-13aa0',
    storageBucket: 'learnfirebase-13aa0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYRmoQL58ibi_lMuICanoErnXCAuCSTyc',
    appId: '1:1086331368779:web:525fd8c33b563b8007e4ce',
    messagingSenderId: '1086331368779',
    projectId: 'learnfirebase-13aa0',
    authDomain: 'learnfirebase-13aa0.firebaseapp.com',
    storageBucket: 'learnfirebase-13aa0.firebasestorage.app',
    measurementId: 'G-VHTLVVZRK7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYRmoQL58ibi_lMuICanoErnXCAuCSTyc',
    appId: '1:1086331368779:web:8964b2f79353494b07e4ce',
    messagingSenderId: '1086331368779',
    projectId: 'learnfirebase-13aa0',
    authDomain: 'learnfirebase-13aa0.firebaseapp.com',
    storageBucket: 'learnfirebase-13aa0.firebasestorage.app',
    measurementId: 'G-LGNHM2TX9X',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX-xqnLFYE5TSuotLM4xC6ffNueeKjv6k',
    appId: '1:1086331368779:ios:1c11496ef741e07507e4ce',
    messagingSenderId: '1086331368779',
    projectId: 'learnfirebase-13aa0',
    storageBucket: 'learnfirebase-13aa0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

}